namespace RainbowSparkleUnicorn {

    export const RAINBOW_SPARKLE_UNICORN_TOUCH_SENSOR_TOUCHED = 5051;
    export const RAINBOW_SPARKLE_UNICORN_TOUCH_SENSOR_RELEASED = 5052;

    export const RAINBOW_SPARKLE_UNICORN_ROTARY_ONE_ROTATING = 5054;
    export const RAINBOW_SPARKLE_UNICORN_ROTARY_TWO_ROTATING = 5055;

    export const RAINBOW_SPARKLE_UNICORN_SWITCH_PRESSED = 5058;
    export const RAINBOW_SPARKLE_UNICORN_SWITCH_RELEASED = 5059;
    export const RAINBOW_SPARKLE_UNICORN_MOTION_STARTED = 5060;
    export const RAINBOW_SPARKLE_UNICORN_MOTION_STOPPED = 5061;
    export const RAINBOW_SPARKLE_UNICORN_MOTION_HALTED = 5062;

    export const RAINBOW_SPARKLE_UNICORN_SOUND_BUSY = 5053;

}