
let MICROBIT_EVT_ANY = 0

let RAINBOW_SPARKLE_UNICORN_TOUCH_SENSOR_TOUCHED = 5051
let RAINBOW_SPARKLE_UNICORN_TOUCH_SENSOR_RELEASED = 5052
let RAINBOW_SPARKLE_UNICORN_SOUND_BUSY = 5053
let RAINBOW_SPARKLE_UNICORN_ROTARY_ONE_ROTATING = 5054
let RAINBOW_SPARKLE_UNICORN_ROTARY_TWO_ROTATING = 5055
let RAINBOW_SPARKLE_UNICORN_ADC_ONE = 5056
let RAINBOW_SPARKLE_UNICORN_ADC_TWO = 5057
let RAINBOW_SPARKLE_UNICORN_SWITCH_PRESSED = 5058
let RAINBOW_SPARKLE_UNICORN_SWITCH_RELEASED = 5059
let RAINBOW_SPARKLE_UNICORN_MOTION_STOPPED = 5060
let RAINBOW_SPARKLE_UNICORN_MOTION_HALTED = 5061
let RAINBOW_SPARKLE_UNICORN_IP_RECEIVED = 5062
let RAINBOW_SPARKLE_UNICORN_MQTT_CONNECTED = 5063
let RAINBOW_SPARKLE_UNICORN_SOUND_SET_VOLUME = 5064
let RAINBOW_SPARKLE_UNICORN_SOUND_SET_TRACK = 5065
let RAINBOW_SPARKLE_UNICORN_I2C_EVENT = 5066