
let MICROBIT_EVT_ANY = 0
let RAINBOW_SPARKLE_UNICORN_TOUCH_SENSOR_TOUCHED = 2001
let RAINBOW_SPARKLE_UNICORN_TOUCH_SENSOR_RELEASED = 2002
let RAINBOW_SPARKLE_UNICORN_SOUND_BUSY = 2003
let RAINBOW_SPARKLE_UNICORN_ROTARY_ONE_ROTATING = 2004
let RAINBOW_SPARKLE_UNICORN_ROTARY_TWO_ROTATING = 2005
let RAINBOW_SPARKLE_UNICORN_ADC_ONE = 2006
let RAINBOW_SPARKLE_UNICORN_ADC_TWO = 2007
let RAINBOW_SPARKLE_UNICORN_SWITCH_PRESSED = 2008
let RAINBOW_SPARKLE_UNICORN_SWITCH_RELEASED = 2009
let RAINBOW_SPARKLE_UNICORN_MOTION_STOPPED = 2010
let RAINBOW_SPARKLE_UNICORN_MOTION_HALTED = 2011
let RAINBOW_SPARKLE_UNICORN_IP_RECEIVED = 2012
let RAINBOW_SPARKLE_UNICORN_MQTT_CONNECTED = 2013
let RAINBOW_SPARKLE_UNICORN_SOUND_SET_VOLUME = 2014
let RAINBOW_SPARKLE_UNICORN_SOUND_SET_TRACK = 2015
let RAINBOW_SPARKLE_UNICORN_I2C_EVENT = 2016

