input.onLogoEvent(TouchButtonEvent.Touched, function () {
    RainbowSparkleUnicorn.Sound.playTrack(24)
    RainbowSparkleUnicorn.Light.turnAllOff()
})
// RainbowSparkleUnicorn.parseRecievedMessage("")
RainbowSparkleUnicorn.start()
RainbowSparkleUnicorn.Sound.setVolume(15)
basic.pause(100)
RainbowSparkleUnicorn.Light.turnAllOn()
RainbowSparkleUnicorn._parseRecievedMessage("")
