input.onLogoEvent(TouchButtonEvent.Touched, function () {
    RainbowSparkleUnicorn.Light.turnAllOff()
    RainbowSparkleUnicorn.Sound.playTrack(24)
})
RainbowSparkleUnicorn.start()
RainbowSparkleUnicorn.printReceivedMessages()
RainbowSparkleUnicorn.comment("set volume")
RainbowSparkleUnicorn.Sound.setVolume(15)
basic.pause(100)
RainbowSparkleUnicorn.Light.turnAllOn()
